#! /bin/sh

sxhkd &

bspc monitor -d I II III

bspc config border_width         2
bspc config window_gap           25

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus 	 true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config -d ^1 top_padding 20
bspc config -d ^2 top_padding 20
bspc config -d ^3 top_padding 20

feh --bg-scale ~/Pictures/backgrounds/89t565gv1hhy.jpg 

~/scripts/startbar.sh &
